### PR TITLE
Options and events

### PR DESCRIPTION
**Pull request by ancapdev**
Very useful package.

I was interested in exposing more of the options and events to the caller, and knocked up this code.

I tried putting together something that was more generic, but couldn't find a good way to map event properties. Ended up hard mapping the two I was interested in, and exposing only a subset of the available events. Be very happy to see a better solution to this.

Left ```onCellValueChanged``` in there to not break any API, but might be good to move forward with a scheme for mapping the underlying JS API in a more consistent fashion.

These events are accessible to the caller through the observables of the returned ```Scope``` object.

### CODE REVIEW

**Comment by pfitzseb** [comment]
Good idea. Honestly, I think we can just deprecate the old API and switch to this, since it seems much cleaner to not have both ways. You wanna take a stab at the deprecation?

**Comment by ancapdev** [comment]
Sure. What do you have in mind for that? Maybe something like
* remove ```cell_changed```
* bind ```onCellValueChanged``` using the new mechanism
* marshal  ```newValue``` and ```oldValue``` when present
* add API to decide which columns are editable

Or do you want the old API available with a warning?

**Comment by pfitzseb** [comment]
Sorry for getting back to you so late, but that sounds like a solid plan. If you're still up for it then I'd love to have that in this PR, otherwise I'll merge this fairly soon and unify the API in a follow up PR.

**Comment by ancapdev** [comment]
Forgot to check on this for a while. Perhaps best to merge and get these in, then follow up with more changes to revamp the API.

**Pull request merged**
